common: &common
  adapter: postgresql
  host: <%= ENV["PG_HOST"] %>
  encoding: unicode
  pool: 5
  port: <%= ENV["PG_PORT"] %>

development: &development
  <<: *common
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  database: vanguard_development

test:
  <<: *development
  database: vanguard_test
